mybatis:
  mapper-locations: classpath:mapper/*.xml

spring:
  datasource:
    username: root
    password: 153615
    url: jdbc:mysql://192.168.1.200/bill?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: false
  mvc:
    hiddenmethod:
      filter:
        enabled: true
